services:
  # Backend API Service
  - type: web
    name: lbm-arena-backend
    env: python
    region: oregon
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false  # Set this to your Supabase PostgreSQL connection string
      - key: REDIS_URL
        fromService:
          type: redis
          name: lbm-arena-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src

  # Frontend Static Site
  - type: static
    name: lbm-arena-frontend
    env: static
    buildCommand: echo "No build needed for static frontend"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

services:
  - type: redis
    name: lbm-arena-redis
    ipAllowList: []
    region: oregon
